# Generated by Django 5.0a1 on 2023-10-17 13:36

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceAtWarehousesLedger_movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrator_id', models.CharField(max_length=36, verbose_name='registrator id')),
                ('line_index', models.PositiveIntegerField(verbose_name='line index across this document')),
                ('enabled', models.BooleanField(default=True, verbose_name='this record activity flag')),
                ('period', models.DateTimeField(verbose_name="record's period")),
                ('action', models.CharField(choices=[('I', 'Income'), ('O', 'Outcome')], max_length=1, verbose_name='action')),
                ('comment', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('registrator_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='registrator content type')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='exampleapp.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='exampleapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('D', 'Draft'), ('A', 'Active')], default='D', max_length=1, verbose_name='document state')),
                ('_deleted', models.BooleanField(default=False, editable=False, verbose_name='marked as deleted')),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='document execution date')),
                ('number_prefix', models.CharField(editable=False, max_length=3, verbose_name='document prefix')),
                ('number_iterator', models.PositiveIntegerField(editable=False, verbose_name='document number (as integer)')),
                ('number', models.CharField(editable=False, max_length=13, verbose_name='document number')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.item')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exampleapp.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exampleapp.warehouse')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['number'], name='exampleapp__number_41610e_hash'), models.Index(fields=['number_prefix', 'number_iterator'], name='exampleapp__number__36e990_idx'), models.Index(fields=['execution_date'], name='exampleapp__executi_4ac5a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceAtWarehousesLedger_totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(verbose_name="record's period")),
                ('amount_total', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='exampleapp.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='exampleapp.warehouse')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['period'], name='exampleapp__period_b20c46_idx'), models.Index(fields=['period', 'warehouse', 'item'], name='exampleapp__period_215966_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='balanceatwarehousesledger_totals',
            constraint=models.UniqueConstraint(models.F('period'), models.F('warehouse'), models.F('item'), name='unique_dimensions_BalanceAtWarehousesLedger_totals'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['period'], name='exampleapp__period_31346a_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['registrator_content_type', 'registrator_id', 'line_index', 'enabled'], name='exampleapp__registr_2338c7_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=django.contrib.postgres.indexes.HashIndex(fields=['registrator_id'], name='exampleapp__registr_92aad9_hash'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['period', 'registrator_content_type', 'registrator_id', 'action', 'enabled'], name='exampleapp__period_d3a9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['period', 'action', 'enabled'], name='exampleapp__period_e9c233_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['period', 'enabled'], name='exampleapp__period_4cae47_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceatwarehousesledger_movements',
            index=models.Index(fields=['period', 'enabled', 'warehouse', 'item'], name='exampleapp__period_8e54a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='balanceatwarehousesledger_movements',
            constraint=models.UniqueConstraint(fields=('period', 'registrator_content_type', 'registrator_id', 'line_index'), name='unique_record'),
        ),
    ]
